### PR TITLE
Add linux-aarch64 job to circleci

### LINKED ISSUE #12: aarch64 support
Can you please add aarch64 releases?

### PR DESCRIPTION
**Pull request by hangyas**
This PR adds a CircleCI job for creating `linux-aarch64` releases. Closes #12

### CODE REVIEW

**Comment by borkdude** [comment]
@hangyas Almost there, except that the config is generated from an .edn file :)

See [generate_circleci.clj](https://github.com/babashka/pod-babashka-etaoin/blob/master/script/generate_circleci.clj)

Also you need to add the new job to the end where there is a list of jobs to run.

**Comment by hangyas** [comment]
oops :facepalm:

**Comment by hangyas** [comment]
I should still commit both files, right?

**Comment by borkdude** [comment]
Yes. I'm not sure why circleci isn't running now...

**Comment by borkdude** [comment]
I'll look into the CircleCI issue, we have had some issues with it since a few days. I'm in contact with one of their engineers about it.

**Comment by borkdude** [comment]
@hangyas Sorry for the trouble, but could you fix the merge conflict? I expect circle to correctly run now when you push again.

**Comment by borkdude** [comment]
Hmm, still no luck. Have you by any chance added the project to your own circleci account?

**Comment by hangyas** [comment]
nope :thinking:

**Comment by borkdude** [comment]
I'll merge to a branch first to see if that works.

**Comment by borkdude** [comment]
It's running here now: https://github.com/babashka/pod-babashka-etaoin/tree/aarch

**Comment by borkdude** [comment]
@hangyas Build is failing. Please make new PRs against the aarch64 branch, at least we've got something running now.

https://app.circleci.com/pipelines/github/babashka/pod-babashka-etaoin/60/workflows/1edffb84-9f61-4c95-a50b-c28eecb62b48/jobs/160

**Pull request merged**
