### PR TITLE
Fix linux-aarch64 CircleCI job

### PR DESCRIPTION
**Pull request by hangyas**

### CODE REVIEW

**Comment by borkdude** [comment]
@hangyas We could skip the tests on the aarch64 machine, I trust that they will work if the binary compiled successfully

**Comment by borkdude** [comment]
Also there's merge conflicts

**Comment by hangyas** [comment]
Sorry for the force push, I think this was the cleanest solution. Also, I'm not sure if moving `resource_class` was necessary, might be out of scope

**Comment by borkdude** [comment]
Awesome. Can you test this binary on your RaspBerry?

https://output.circle-artifacts.com/output/job/ff357cef-a12f-40cf-a971-4e57dcabc322/artifacts/0/release/pod-babashka-etaoin-0.1.0-linux-aarch64.zip

You can load a pod from a local path using:

```
(babashka.pods/load-pod "/path/to/pod-babashka-etaoin")
```

**Comment by hangyas** [comment]
Seems like the binary itself is working, but I keep getting timeouts when I try to create a driver, so I can't run the tests or anything useful. I'll try to figure it out tomorrow

**Comment by hangyas** [comment]
```
> POD_TEST_ENV=native bb test

Running tests in #{"test"}
Testing native version

Testing pod.babashka.etaoin-test

Ran 1 tests containing 15 assertions.
0 failures, 0 errors.
```

**Comment by borkdude** [comment]
Excellent!

**Pull request merged**
